heat_template_version: 2014-10-16
description: create a keypair.
parameters:
  keypair_name_prefix:
    type: string
    label: key Name prefix
    description: the keypair name.
    default: mykeypair
resources:
  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: $prefix-$stack
          params:
            $prefix: { get_param: keypair_name_prefix }
            $stack : { get_param: "OS::stack_name" }
      save_private_key: true

outputs:
   keypair_name:
      description: Your key pair name
      value:
         str_replace:
           template: $prefix-$stack
           params:
              $prefix: { get_param: keypair_name_prefix }
              $stack : { get_param: "OS::stack_name" }
   my_private_key:
     value: { get_attr: [keypair, private_key] }
