heat_template_version: 2014-10-16

description: create EIP and snat

parameters:
  name:
    type: string
    label: Name or ID
    description: Name to be used for compute instance
    default: FEtest001
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: OBS_U_RHEL_6.8
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    #default: set_your-own_keypair
  flavor:
    type: string
    label: flavor name
    description: Name of flavor to be used for compute instance
    default: s1.medium
  network:
    type: string
    label: Network name or ID
    description: Network to attach server to.
    #default: use_your-own_network
  availability_zone:
    type: string
    label: availability_zone
    description: availability zone.
    default: as-south-0a
  fip_pool:
    type: string
    label: Public FIP pool name or ID
    description: Public Floating IP Network to attach server to.
    default: admin_external_net

resources:
  vpc:
    type: OS::Neutron::Router
    properties:
      name: test-router
      external_gateway_info:
        network: { get_param: fip_pool }
        enable_snat: true
  network_port:
    depends_on: vpc
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
  fip:
    depends_on: instance1
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: fip_pool }
      port_id: { get_resource: network_port }

  instance1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name } 
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      availability_zone: { get_param: availability_zone }
      networks:
        - port: { get_resource: network_port }

outputs:
  FIP:
    description: The value of FIP
    value: { get_attr: [fip, floating_ip_address]}