heat_template_version: 2015-10-15

description: create a subnet with an existing VPC.first create a subnet and then use Router interfaces associate routers with subnet.

parameters:
  my_router:
    type: string
    label: the existing vpc this subnet belongs to
    description: the existing vpc,use the command cli :neutron router list.
    #default: to choose you own vpc
    default: c489f324-b131-48e1-a11d-d5f94b4eda91
  cidr:
    type: string
    label: cidr
    description: cidr value.
    default: 192.168.6.0/24
  dns:
    type: string
    label: dns
    description: dns server.
    default: 100.125.0.41

resources:
  my_network:
    type: OS::Neutron::Net
    properties:
      name: test-network

  my_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: test-subnet
      network: { get_resource: my_network }
      cidr: { get_param: cidr }
      dns_nameservers:
        - { get_param: dns }
  my_router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_param: my_router }
      subnet: { get_resource: my_subnet }
