heat_template_version: 2015-10-15

description: Advanced template to deploy an autoscaling group 

parameters:
resources:
  autoscaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 2
      min_size: 2
      max_size: 4
      resource:
        type: instance.yaml
        properties:
          name: my-autoscaling-instance001-%index%

  autoscaling_group_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: autoscaling_group }
      cooldown: 60
      scaling_adjustment: 1

  autoscaling_group_cpu_alarm_high:
    type: OSE::CES::Alarm
    properties:
      description: Scale-up if the average CPU greater than 50% for 1 minute
      meter_name: cpu_util
      resource_id: { get_resource: autoscaling_group }
      statistic: max
      period: 300
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - { get_attr: [ autoscaling_group_scaleup_policy, alarm_url] }
      matching_metadata: {'metadata.user_metadata.group': 'autoscaling_group' }
      comparison_operator: gt

  autoscaling_group_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: autoscaling_group }
      cooldown: 60
      scaling_adjustment: -1

  autoscaling_group_cpu_alarm_low:
    type: OSE::CES::Alarm
    properties:
      description: Scale-down if the average CPU less than 15% for 5 minutes
      meter_name: cpu_util
      resource_id: { get_resource: autoscaling_group }
      statistic: max
      period: 300
      evaluation_periods: 4
      threshold: 15
      alarm_actions:
        - { get_attr: [ autoscaling_group_scaledown_policy, alarm_url] }
      matching_metadata: {'metadata.user_metadata.group': 'autoscaling_group' }
      comparison_operator: lt

outputs:
  ids:
    description: The ids of the cluster.
    value: { get_attr: [autoscaling_group, outputs_list, id] }
  ips:
    description: The ips address of the cluster.
    value: { get_attr: [autoscaling_group, outputs_list, ip] }
